language: java
sudo: false
install: true
jdk:
  - oraclejdk8

addons:
  sonarqube:
    organization: ${SONAR_ORGANIZATION}
    token:
      secure: ${SONAR_TOKEN}

script:
  - ./travis.sh

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar
    - $HOME/jvm
    - $HOME/maven
